[book]
title = "HBML Tutorial"
description = "A HBML tutorial and documentation by the HBML devs"
authors = ["heyitsdoodler", "nxe (RosiePuddles)"]
language = "en"
[output.html]
[output.compress]
subtitle = "How to use HBML from simple markdown to complex macros"
highlight = "no-node"